language: node_js
node_js:
- "12"
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
after_script:
 - cat reports/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c8c40bc13ee38867f698
    on_success: change
    on_failure: always
    on_start: never
addons:
  chrome: beta
script:
- yarn run test
- node language/travis.js
