name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - 16
    steps:
    - uses: actions/checkout@v2
    - name: Set up system
      run: bin/before_install
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: ${{ !env.ACT && 'yarn' || '' }}
        registry-url: https://npm.manageiq.org/
    - name: Prepare tests
      run: bin/setup
    - name: Run tests
      run: yarn run test
    - name: Report code coverage
      if: ${{ github.ref == 'refs/heads/master' }}
      continue-on-error: true
      run: cat reports/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
